#!/usr/bin/env python3
"""Platform tickets: one folder tree, like Brain (product / area / ticket), with generated indexes.

Layout: docs/bugs/pulse_platform/<product>/<area>/plat-NNN.md. Every ticket starts with the same header table
(State, Priority, Product, Area, Summary). Every folder has a generated index.md; the top one is the map, with the
newest tickets. There is no separate register (owner decision 2026-10-06, like Brain). Never edit an index by hand:
edit the ticket, then run `scripts/tickets.py index`.

  scripts/tickets.py new --product brain --area access --priority P2 "Title"   create the next ticket
  scripts/tickets.py index                                                     regenerate the indexes
  scripts/tickets.py check                                                     fail if anything is stale (CI)
  scripts/tickets.py migrate                                                   one-time conversion (2026-10-06)
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUGS = ROOT / 'docs' / 'bugs'
TICKETS = BUGS / 'pulse_platform'
REGISTER = BUGS / 'pulse_platform_issue_register.md'
GUIDE = TICKETS / 'README.md'

PRODUCTS = {
    'platform': 'Platform (shared runtime, sandbox, CLIs, chat, browser, integrations)',
    'goals': 'Goals (workflows: steps, plans, Pulse, evaluation)',
    'crew': 'Crew', 'code': 'Code', 'relays': 'Relays', 'vault': 'Vault', 'brain': 'Brain',
    'video-studio': 'Video Studio', 'sparkquill': 'SparkQuill', 'dominion': 'Dominion',
}
STATES = ('open', 'in progress', 'fixed on main', 'deployed', 'closed')
PRIORITIES = ('P0', 'P1', 'P2', 'P3', '-')
GOALS_AREAS = {'step-execution', 'plans-contracts', 'pulse-governance', 'evaluation', 'human-decisions'}
HEADER_FIELDS = ('State', 'Priority', 'Product', 'Area', 'Summary')
GENERATED = '<!-- Generated by scripts/tickets.py: do not edit. Edit the tickets, then run `scripts/tickets.py index`. -->'


def ticket_number(path):
    m = re.search(r'plat-(\d+)', path.name)
    return int(m.group(1)) if m else None


def ticket_files():
    return sorted(p for p in TICKETS.rglob('*.md') if p.name not in ('index.md', 'README.md') and ticket_number(p) is not None)


def read_header(text):
    """The standard header table: | Field | Value | rows right after the title."""
    fields = {}
    m = re.search(r'^\| Field \| Value \|\n\|---\|---\|\n((?:\|.*\|\n)+)', text, re.M)
    if m:
        for row in m.group(1).splitlines():
            cells = [c.strip() for c in row.strip('|').split('|', 1)]
            if len(cells) == 2 and cells[0] in HEADER_FIELDS:
                fields[cells[0]] = cells[1].replace('\\|', '|')
    return fields, m


def header_table(fields):
    rows = ''.join(f"| {k} | {str(fields.get(k, '')).replace('|', chr(92) + '|')} |\n" for k in HEADER_FIELDS)
    return '| Field | Value |\n|---|---|\n' + rows


def title_of(text, path):
    m = re.search(r'^# (.+)$', text, re.M)
    if m:
        return re.sub(r'^PLAT-\d+\s*[—:-]+\s*', '', m.group(1)).strip()
    return path.stem


def load():
    out = []
    for path in ticket_files():
        text = path.read_text()
        fields, _ = read_header(text)
        rel = path.relative_to(TICKETS)
        out.append({'path': path, 'rel': rel.as_posix(), 'n': ticket_number(path), 'title': title_of(text, path), **fields})
    return out


def rel_link(from_dir, target):
    return os.path.relpath(target, from_dir).replace(os.sep, '/')


def render_index(folder, tickets):
    """index.md for one folder: its subfolders (name and count only) and the tickets directly in it."""
    rel = folder.relative_to(TICKETS)
    depth = len(rel.parts)
    title = 'Platform tickets' if depth == 0 else ' / '.join(PRODUCTS.get(p, p) if i == 0 else p for i, p in enumerate(rel.parts))
    lines = [GENERATED, '', f'# {title}', '']
    if depth == 0:
        lines += ['How tickets work: [README](README.md). Each folder lists its own tickets.', '']
    subs = sorted(d for d in folder.iterdir() if d.is_dir())
    if subs:
        lines += ['| Folder | Tickets | Open |', '|---|---|---|']
        for d in subs:
            inside = [t for t in tickets if Path(t['path']).is_relative_to(d)]
            opened = sum(1 for t in inside if t.get('State') in ('open', 'in progress'))
            label = PRODUCTS.get(d.name, d.name) if depth == 0 else d.name
            lines.append(f"| [{label}]({d.name}/index.md) | {len(inside)} | {opened} |")
        lines.append('')
    if depth == 0:
        recent = sorted(tickets, key=lambda t: (-t['n'], t['rel']))[:40]
        lines += ['## Newest tickets', '', '| Ticket | Title | State | Priority | Folder |', '|---|---|---|---|---|']
        for t in recent:
            folder_rel = Path(t['rel']).parent.as_posix()
            lines.append(f"| [PLAT-{t['n']:03d}]({t['rel']}) | {t['title'].replace('|', chr(92) + '|')} | {t.get('State', '')} | {t.get('Priority', '')} | [{folder_rel}]({folder_rel}/index.md) |")
        lines.append('')
    here = sorted((t for t in tickets if Path(t['path']).parent == folder), key=lambda t: -t['n'])
    if here:
        lines += ['| Ticket | Title | State | Priority |', '|---|---|---|---|']
        for t in here:
            name = Path(t['path']).name
            lines.append(f"| [PLAT-{t['n']:03d}]({name}) | {t['title'].replace('|', chr(92) + '|')} | {t.get('State', '')} | {t.get('Priority', '')} |")
        lines.append('')
    return '\n'.join(lines)


def generated_files():
    tickets = load()
    files = {}
    for folder in [TICKETS] + sorted(d for d in TICKETS.rglob('*') if d.is_dir()):
        files[folder / 'index.md'] = render_index(folder, tickets)
    return files, tickets


def problems(tickets):
    out = []
    seen = {}
    for t in tickets:
        rel = t['rel']
        parts = Path(rel).parts
        if len(parts) != 3:
            out.append(f'{rel}: tickets live at <product>/<area>/plat-NNN.md')
            continue
        for field in HEADER_FIELDS[:4]:
            if not t.get(field):
                out.append(f'{rel}: header field {field} is missing')
        if t.get('State') and t['State'] not in STATES:
            out.append(f"{rel}: State must be one of {', '.join(STATES)}")
        if t.get('Priority') and t['Priority'] not in PRIORITIES:
            out.append(f"{rel}: Priority must be one of {', '.join(PRIORITIES)}")
        if t.get('Product') and (t['Product'] != parts[0] or t['Product'] not in PRODUCTS):
            out.append(f"{rel}: Product must match its folder and be one of {', '.join(PRODUCTS)}")
        if t.get('Area') and t['Area'] != parts[1]:
            out.append(f'{rel}: Area must match its folder')
        seen.setdefault(t['n'], []).append(rel)
    known = {339, 373, 496}  # numbers given twice before 2026-10-06; both tickets are kept
    for n, rels in seen.items():
        if len(rels) > 1 and n not in known:
            out.append(f'PLAT-{n:03d} is used by {len(rels)} tickets: {rels}')
    return out


def cmd_index(_):
    files, _ = generated_files()
    for path, text in files.items():
        path.write_text(text)
    print(f'wrote {len(files)} generated files')


def cmd_check(_):
    files, tickets = generated_files()
    issues = problems(tickets)
    stale = [str(p.relative_to(ROOT)) for p, text in files.items() if not p.exists() or p.read_text() != text]
    stale_idx = [str(p.relative_to(ROOT)) for p in TICKETS.rglob('index.md') if p not in files]
    for msg in issues + [f'{s} is out of date: run scripts/tickets.py index' for s in stale + stale_idx]:
        print(msg, file=sys.stderr)
    if issues or stale or stale_idx:
        sys.exit(1)
    print(f'{len(tickets)} tickets, indexes current')


def cmd_new(args):
    if args.product not in PRODUCTS:
        sys.exit(f"product must be one of {', '.join(PRODUCTS)}")
    if not re.fullmatch(r'[a-z0-9-]+', args.area):
        sys.exit('area must be lower-case words joined by hyphens')
    n = max((ticket_number(p) or 0) for p in ticket_files()) + 1
    folder = TICKETS / args.product / args.area
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f'plat-{n:03d}.md'
    back = 'index.md'
    fields = {'State': 'open', 'Priority': args.priority, 'Product': args.product, 'Area': args.area, 'Summary': args.summary or ''}
    path.write_text(f"[← {args.product} / {args.area}]({back})\n\n# PLAT-{n:03d}: {args.title}\n\n{header_table(fields)}\n## What happened\n\n## Fix\n\n## Left\n")
    cmd_index(None)
    print(path.relative_to(ROOT))


# ---------------------------------------------------------------- one-time migration (2026-10-06)

def classify_product(title, area):
    t = title.lower()
    rules = [('sparkquill', r'sparkquill'), ('dominion', r'dominion'), ('video-studio', r'video studio|video-studio'),
             ('brain', r'\bbrain\b|knowledge ?base|knowledgebase|\bkb\b'), ('vault', r'\bvault'),
             ('relays', r'\brelays?\b'), ('crew', r'\bcrews?\b'),
             ('code', r'\bcode (project|workspace|chat|product|tab|terminal|review)|\bcode product|private coding workspace')]
    for product, pattern in rules:
        if re.search(pattern, t):
            return product
    return 'goals' if area in GOALS_AREAS else 'platform'


def classify_state(text):
    t = text.lower()
    if re.search(r"won't fix|wontfix|not a platform issue|superseded|obsolete|\bremoved\b|\bclosed\b|no repository fix|third-party", t):
        return 'closed'
    if re.search(r'not (yet )?deployed|fixed on main|on main,|on main\.|implemented and tested locally|deployment is pending|deploy pending', t):
        return 'fixed on main'
    if re.search(r'\bdeployed\b|is live|green in rts|released|verified live|healthy in rts', t):
        return 'deployed'
    if re.search(r'in progress|being worked|partial', t):
        return 'in progress'
    if re.search(r'`implemented`|\bimplemented\b|\bfixed\b|\bresolved\b', t):
        return 'fixed on main'
    return 'open'


def first_sentence(text, limit=220):
    text = re.sub(r'\s+', ' ', re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)).strip()
    text = re.sub(r'^PLAT-\d+,?\s*(P[0-3],?\s*)?', '', text)
    m = re.match(r'(.+?[.!?])(\s|$)', text)
    s = (m.group(1) if m else text).strip()
    return s if len(s) <= limit else s[:limit - 1].rstrip() + '…'


def parse_register_blocks(reg):
    """Per-ticket prose keyed by ticket path, and the narrative sections that are not about one ticket."""
    blocks, narrative = {}, []
    parts = re.split(r'(?m)^(#{1,3} .+)$', reg)
    preamble = parts[0].strip()
    if preamble:
        narrative.append(('Notes kept from the old register', preamble))
    for i in range(1, len(parts), 2):
        heading, body = parts[i], parts[i + 1]
        m = re.match(r'#{1,3} (.+?)\s+—\s+PLAT-\d+', heading)
        link = re.search(r'\]\((pulse_platform/[^)]+\.md)\)', body)
        if m and link:
            blocks.setdefault(link.group(1), []).append((m.group(1).strip(), body.strip()))
        elif heading.strip('# ').strip() in ('Pulse Platform-Issue Register',) and not body.strip():
            continue
        else:
            narrative.append((heading.strip('# ').strip(), body.strip()))
    return blocks, narrative


def legacy_fields(text):
    f = {}
    for key, pattern in (('state', r'^\| (?:Ticket state|State|Status) \| `?([^`|]+)`? \|'), ('priority', r'(?:^\| Priority \| |\*\*Priority:\*\* ?)`?(P[0-3])')):
        m = re.search(pattern, text, re.M)
        if m:
            f[key] = m.group(1).strip()
    m = re.search(r'^\*\*State:\*\* (.+)$', text, re.M)
    if m:
        f['state'] = m.group(1)
    return f


def cmd_migrate(_):
    if any((TICKETS / p).is_dir() for p in PRODUCTS):
        sys.exit('already migrated')
    reg = REGISTER.read_text()
    blocks, narrative = parse_register_blocks(reg)
    plan = []
    for path in ticket_files():
        old_rel = path.relative_to(TICKETS).as_posix()
        area = path.parent.name
        text = path.read_text()
        reg_blocks = blocks.get(f'pulse_platform/{old_rel}', [])
        title = reg_blocks[0][0] if reg_blocks else title_of(text, path)
        reg_text = ' '.join(b for _, b in reg_blocks)
        legacy = legacy_fields(text)
        prio = re.search(r'\b(P[0-3])\b', reg_text[:400]) or re.search(r'\b(P[0-3])\b', legacy.get('priority', ''))
        state_src = reg_text[:600] if reg_text else legacy.get('state', '') + ' ' + text[:1500]
        product = classify_product(title, area)
        plan.append({'old': path, 'new': TICKETS / product / area / path.name, 'title': title, 'reg': reg_blocks,
                     'fields': {'State': classify_state(state_src), 'Priority': prio.group(1) if prio else '-',
                                'Product': product, 'Area': area, 'Summary': first_sentence(reg_blocks[0][1]) if reg_blocks else ''}})
    mapping = {p['old'].resolve(): p['new'] for p in plan}
    for p in plan:
        p['new'].parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(['git', 'mv', str(p['old']), str(p['new'])], check=True, cwd=ROOT)
    # Rewrite links everywhere in the repository's text files.
    old_to_new = {f"pulse_platform/{p['old'].relative_to(TICKETS).as_posix()}": f"pulse_platform/{p['new'].relative_to(TICKETS).as_posix()}" for p in plan}
    pattern = re.compile('|'.join(re.escape(k) for k in sorted(old_to_new, key=len, reverse=True)))
    tracked = subprocess.run(['git', 'ls-files'], capture_output=True, text=True, cwd=ROOT, check=True).stdout.split()
    for f in tracked:
        fp = ROOT / f
        if fp == REGISTER or fp.suffix not in ('.md', '.go', '.ts', '.tsx', '.py', '.yml', '.yaml', '.json', '.sh') or not fp.is_file():
            continue
        s = fp.read_text(errors='ignore')
        s2 = pattern.sub(lambda m: old_to_new[m.group(0)], s)
        if fp.parent != TICKETS and not fp.is_relative_to(TICKETS):
            s2 = s2.replace('pulse_platform_issue_register.md', 'pulse_platform/index.md')
        if s2 != s:
            fp.write_text(s2)
    # Inside tickets: relative links to other tickets and to the register.
    link = re.compile(r'\]\(((?:\.\./|\./)?[^)\s]*?\.md)(#[^)]*)?\)')
    for p in plan:
        new_dir, old_dir = p['new'].parent, p['old'].parent
        text = p['new'].read_text()

        def fix(m):
            target, anchor = m.group(1), m.group(2) or ''
            if target.startswith(('http', '/')):
                return m.group(0)
            old_abs = (old_dir / target).resolve()
            new_abs = mapping.get(old_abs, old_abs)
            if not new_abs.exists() and old_abs not in mapping:
                return m.group(0)
            return '](' + rel_link(new_dir, new_abs) + anchor + ')'
        text = re.sub(r'^\[←[^\]]*\]\([^)]*pulse_platform_issue_register\.md\)', f"[← {p['fields']['Product']} / {p['fields']['Area']}](index.md)", text, flags=re.M)
        text = text.replace('pulse_platform_issue_register.md', rel_link(new_dir, TICKETS / 'index.md'))
        text = link.sub(fix, text)
        lines = text.split('\n')
        at = next((i for i, l in enumerate(lines) if l.startswith('# ')), None)
        table = header_table(p['fields']).rstrip('\n').split('\n')
        if at is None:
            lines = [f"# PLAT-{ticket_number(p['new']):03d}: {p['title']}", ''] + table + [''] + lines
        else:
            lines = lines[:at + 1] + [''] + table + lines[at + 1:]
        text = '\n'.join(lines)
        if p['reg']:
            text = text.rstrip('\n') + '\n\n## Register notes\n\n' + '\n\n'.join(body for _, body in p['reg']) + '\n'
            text = link.sub(lambda m: m.group(0) if not m.group(1).startswith('pulse_platform/') else '](' + rel_link(new_dir, (BUGS / m.group(1)).resolve()) + (m.group(2) or '') + ')', text)
        p['new'].write_text(text)
    for d in sorted((d for d in TICKETS.iterdir() if d.is_dir() and d.name not in PRODUCTS), reverse=True):
        if not any(d.rglob('*')):
            d.rmdir()
    guide = ['# How platform tickets work', '',
             'Tickets live at `<product>/<area>/plat-NNN.md`, like Brain: product folders, area folders inside them, and a generated `index.md` in every folder. The top [index](index.md) is the map, with the newest tickets. There is no separate register.', '',
             'Every ticket starts with the same header table: State (open, in progress, fixed on main, deployed, closed), Priority (P0 to P3, or -), Product (its top folder), Area (its folder) and a one-line Summary. Edit the ticket, never an index.', '',
             '- New ticket: `scripts/tickets.py new --product <product> --area <area> --priority P2 "Title"` (takes the next number).',
             '- After editing tickets: `scripts/tickets.py index`. CI runs `scripts/tickets.py check`.', '',
             'Products: ' + ', '.join(f'`{k}` ({v})' for k, v in PRODUCTS.items()) + '.', '']
    for heading, body in narrative:
        if body:
            guide += [f'## {heading}', '', body, '']
    GUIDE.write_text('\n'.join(guide))
    subprocess.run(['git', 'rm', '-q', str(REGISTER)], check=True, cwd=ROOT)
    cmd_index(None)
    print(f'migrated {len(plan)} tickets')


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='cmd', required=True)
    sub.add_parser('index')
    sub.add_parser('check')
    sub.add_parser('migrate')
    new = sub.add_parser('new')
    new.add_argument('--product', required=True)
    new.add_argument('--area', required=True)
    new.add_argument('--priority', default='-', choices=PRIORITIES)
    new.add_argument('--summary', default='')
    new.add_argument('title')
    args = parser.parse_args()
    {'index': cmd_index, 'check': cmd_check, 'migrate': cmd_migrate, 'new': cmd_new}[args.cmd](args)


if __name__ == '__main__':
    main()
